### ISSUE TITLE
Add https-certificate block to two Cobalt Strike profiles at Teamserver instance startup

### ISSUE THREAD

**Issue by dav3r** [cisagov/cool-assessment-terraform#116]
# 💡 Summary #

Teamserver instances should fetch the TLS certificate for their specified domain from our S3 certificates bucket (if available) and then appropriately modify the `amazon.profile` and `ocsp.profile` files to include a valid `https-certificate` section.

## Motivation and context ##

In https://github.com/cisagov/cool-system/issues/90, we are working to remove the need to use [`ServerSetup.sh`](https://github.com/noahpowers/ServerSetup).  One of the acceptance criteria for this is to replicate the functionality of the [`httpsc2doneright()` function from `ServerSetup.sh`](https://github.com/noahpowers/ServerSetup/blob/master/serversetup.sh#L587-L633).

## Implementation notes ##

This issue does NOT include figuring out how the certificate is created and put in our S3 bucket. Initially, that will be a manual process that we want to automate in the future.

## Acceptance criteria ##

- [ ] When a Teamserver instance is deployed, the `amazon.profile` and `ocsp.profile` files each contain a valid `https-certificate` section.
- [ ] Cobalt Strike is able to successfully utilize the updated profiles for HTTPS (probably have to work with an assessment operator to validate this).
- [ ] If a certificate for the specified domain is NOT found in S3, a warning is logged and the Cobalt Strike profiles are not touched.

**Comment by jsf9k** [comment]
@dav3r, I was looking at grabbing the certificate and adding the necessary configuration to the Cobalt Strike profiles via `cloud-init`.  That would require us to create the certificate for the teamserver _before_ running the `terraform apply` for the assessment environment, and it would also require us to include the teamserver FQDN in the tfvars file when we run said `terraform apply`. 
 Does this agree with what you had in mind?

**Comment by dav3r** [comment]
> @dav3r, I was looking at grabbing the certificate and adding the necessary configuration to the Cobalt Strike profiles via `cloud-init`. That would require us to create the certificate for the teamserver _before_ running the `terraform apply` for the assessment environment, and it would also require us to include the teamserver FQDN in the tfvars file when we run said `terraform apply`.
> Does this agree with what you had in mind?

Yes, that is what I had in mind.  We already have to create the Guacamole certificate before we run `terraform apply`, so I figured this would follow a similar process.  Also, don't forget that [we have cloud-init code that fetches the Guac cert from S3 and deploys it](https://github.com/cisagov/cool-assessment-terraform/blob/develop/cloud-init/install-certificates.py).

As for the teamserver FQDN, that is already in the tfvars file:
https://github.com/cisagov/cool-assessment-terraform/blob/5845d3425da85513d2b420af06db6d3915cf4a97/variables.tf#L64-L68

**Comment by jsf9k** [comment]
> > @dav3r, I was looking at grabbing the certificate and adding the necessary configuration to the Cobalt Strike profiles via `cloud-init`. That would require us to create the certificate for the teamserver _before_ running the `terraform apply` for the assessment environment, and it would also require us to include the teamserver FQDN in the tfvars file when we run said `terraform apply`.
> > Does this agree with what you had in mind?
> 
> Yes, that is what I had in mind. We already have to create the Guacamole certificate before we run `terraform apply`, so I figured this would follow a similar process. Also, don't forget that [we have cloud-init code that fetches the Guac cert from S3 and deploys it](https://github.com/cisagov/cool-assessment-terraform/blob/develop/cloud-init/install-certificates.py).
> 
> As for the teamserver FQDN, that is already in the tfvars file:
> https://github.com/cisagov/cool-assessment-terraform/blob/5845d3425da85513d2b420af06db6d3915cf4a97/variables.tf#L64-L68

Yep, I was going to reuse that cert-fetching code.  Thanks for pointing out that the teamserver FQDN variable already exists - I didn't realize that.

**Comment by jsf9k** [comment]
> As for the teamserver FQDN, that is already in the tfvars file:

@dav3r, it looks like that variable is actually only the domain - e.g., `example.com` vice `mail.example.com`.  Are we creating a wildcard cert for the domain and using that for the teamserver host?

**Comment by dav3r** [comment]
I was thinking that we would use wildcard certs since I haven't heard any reasons why we can't.
