### ISSUE TITLE
Support multiple email-sending domains per assessment

### ISSUE THREAD

**Issue by dav3r** [cisagov/cool-assessment-terraform#127]
# 💡 Summary #

Enable an assessment to have more than one email-sending domain.

## Motivation and context ##

Some types of assessments require multiple instances (e.g. Teamservers), where each instance sends email from a different domain.  Currently, our `email_sending_domain` variable only supports a single domain.

## Implementation notes ##

Convert the `email_sending_domain` variable from a string to a list.

## Acceptance criteria ##

- [ ] Terraform and cloud-init function correctly with no email-sending domains, a single Teamserver, and a single Gophish instance
- [ ] Terraform and cloud-init function correctly with a single email-sending domain, a single Teamserver, and a single Gophish instance
- [ ] Terraform and cloud-init function correctly with two email-sending domains, two Teamservers, and two Gophish instances
- [ ] Documentation explains how list of email-sending domains is applied to instances that send mail (teamserver, gophish).

**Comment by jsf9k** [comment]
As part of this work, please update the description for the `email_sending_domain` variable to make it clear that the FQDN is expected.

**Comment by dav3r** [comment]
According to @kyleevers, multiple email-sending domains are almost never used in a single RPT environment, so implementing this feature is not as important as previously thought.
