### ISSUE TITLE
Modify default Guacamole admin password

### ISSUE THREAD

**Issue by dav3r** [cisagov/cool-assessment-terraform#20]
Currently, when the Guacamole instance is deployed, it has default credentials for the admin user.  Modify this so that a new password is applied (probably should be pulled from the SSM Parameter Store).

**Comment by dav3r** [comment]
This is a much lower priority (possibly does not need to be done at all) now that we have "Kerberized" Guacamole:
* https://github.com/cisagov/cool-system/issues/50
* https://github.com/cisagov/cool-system/issues/13

**Comment by dav3r** [comment]
@jsf9k or @felddy - Can you think of any way that a Guacamole instance can now be accessed without authenticating via Kerberos?  If the answer is "Nope", then I think we can close out this ticket as OBE.

**Comment by jsf9k** [comment]
That should not be possible, short of coming in via the control plane.  I think this ticket can be closed.

**Comment by dav3r** [comment]
Sounds like this issue is now Overcome By Events (OBE).  Thanks!
