### ISSUE TITLE
Globally rename Assessor Portal to Assessor Workbench

### ISSUE THREAD

**Issue by jsf9k** [cisagov/cool-assessment-terraform#212]
# 🐛 Summary #

The [cisagov/assessor-portal-packer](https://github.com/cisagov/assessor-portal-packer) repo was renamed to [cisagov/assessor-workbench-packer](https://github.com/cisagov/assessor-workbench-packer), and the name of the resulting AMI was changed in cisagov/assessor-workbench-packer#31 from `assessor-portal-hvm-${local.timestamp}-x86_64-ebs` to `assessor-workbench-hvm-${local.timestamp}-x86_64-ebs`.  The new name more closely matches what folks are calling the tool.  The AMI name was unfortunately not updated in this repository, so the refreshed AMIs with the newer name are not being used.

The AMI name should be updated, and all resource names, etc. that reference the old "Assessor Portal" language should be updated to instead reference "Assessor Workbench".  Note that the name of the instance type corresponding to the Assessor Workbench would need to be updated in the `inbound_ports_allowed` and `operations_instance_counts` input variables, so this is a breaking change.

**Comment by lfilip-ivaal** [comment]
Should be closed by this PR:

https://github.com/cisagov/cool-assessment-terraform/pull/216

**Comment by jsf9k** [comment]
Resolves by #216.
