### ISSUE TITLE
Would it really hurt anything to move terraformer instance to e.g. t3.medium?

### ISSUE THREAD

**Issue by S4lt5** [cisagov/cool-assessment-terraform#237]
Not sure how many are live, but at .04/hr vs .16/hr for a t3.medium vs t3.xlarge changing even one instance saves ~$1000/yr, and the cpu need for these things is probably pretty minimal.

**Comment by jsf9k** [comment]
The bump up to `t3.xlarge` [was specifically requested by our users](https://github.com/cisagov/cool-assessment-terraform/pull/152).

**Comment by jsf9k** [comment]
@S4lt5 - Please let me know if this issue can be closed.

**Comment by jsf9k** [comment]
I'll go ahead and close this issue.  @S4lt5 - please reopen the issue if you feel there is more to discuss.
