### ISSUE TITLE
EFS mount inconsistent with PentestPortal EC2 instances

### ISSUE THREAD

**Issue by jsf9k** [cisagov/cool-assessment-terraform#85]
# 🐛 Bug Report

When PentestPortal EC2 instances are spun up, the EFS mount sometimes fails.

## To Reproduce

- Spin up several PentestPortal EC2 instances
- Check to see if any have an attempted EFS mount that failed

## Expected behavior

The EFS mounts should always be available on PentestPortal instances.

**Comment by dav3r** [comment]
This morning, we were informed that a freshly-created environment (`env11`) was found to have its 4 Kali instances created without successful EFS volume mounts.  Running `sudo mount -a` resulted in successful mounting of the share, but it's unclear why this problem occurred.

**Comment by jsf9k** [comment]
> This morning, we were informed that a freshly-created environment (`env11`) was found to have its 4 Kali instances created without successful EFS volume mounts. Running `sudo mount -a` resulted in successful mounting of the share, but it's unclear why this problem occurred.

I think the problem was made less likely by 638f182, but obviously it was not completely eliminated.  I think the issue is that Terraform has no way to distinguish between the "resource created" and "resource created and ready for use" states.  In the case that @dav3r mentioned, I suspect that the share was created but did not become available for attachment until _after_ the Kali instances had already booted up and automounted the mounts listed in `/etc/fstab`.

A way to remedy this is to add a simple shell to the cloud-init configuration that will attempt to mount the share in a loop until successful.  This way the share _will_ get mounted even if the instance slips through the crack left by the Terraform dependency.

What do you think, @dav3r?

**Comment by dav3r** [comment]
@jsf9k That makes sense to me- I'm on board with your plan.
